# Generated by Django 3.2.13 on 2022-11-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_movie',
            field=models.ManyToManyField(related_name='liked_movie', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_comment',
            field=models.ManyToManyField(related_name='user_comment', to='movies.Comment'),
        ),
    ]
