# Generated by Django 3.2.13 on 2022-11-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0002_auto_20221121_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked_movie',
            field=models.ManyToManyField(related_name='r_liked_movie', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_comment',
            field=models.ManyToManyField(related_name='r_user_comment', to='movies.Comment'),
        ),
    ]
